<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>DustInTheWind.$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>DustInTheWind.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Description>A WPF control that displays a clock. It supports templates.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>clock;wpf</PackageTags>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageReleaseNotes>More templates added and fixed the existing ones.Added the Static Movement. (Time Providers were renamed to Movements)</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Update="changelog.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Update="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
